title: <p align="center"> Aishwarya K Shetty </p>
logo: /assets/img/logo.jpeg
description:
  <p align="center">
  <a href="https://www.linkedin.com/in/aishwarya-k-shetty-269a3b186">LinkedIn</a> |
  <a href="https://github.com/shettyai">GitHub</a>
  
  <br>   
  I'm working on Data Science, Big Data, Spark, Machine learning & NLP related problems.
  Also handing the Big Data from real-time Ad call data.
  Worked with IBM Research at Big Data Analytics team.
  Working in AdTech domain for 3 years.
  <br>
  </p>



theme: jekyll-theme-minimal
