title: Minimal theme
title: <p align="center"> Aishwarya K Shetty</p>
logo: /assets/img/logo.jpeg
description: 
<p align="center">
  #<a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/aishwarya-k-shetty-269a3b186">LinkedIn</a> |
  <a href="https://github.com/shettyai">GitHub</a>
  
  <br>   
 I am currently working as technical consultant at VMware
  <br>
  </p>
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
