title: <p align="center"> Aishwarya K Shetty </p>
logo: /assets/img/logo.jpeg
description:
  <p align="center">
  <a href="https://www.linkedin.com/in/aishwarya-k-shetty-269a3b186">LinkedIn</a> |
  <a href="https://github.com/shettyai">GitHub</a>
  
  <br>   
  I'm working on Data Science, Big Data, Machine learning & NLP related problems.
  Currently working as Technical Support Engineer at VMware Software India Pvt Limited 
  Over 18 months experience in handlig customer with virtualization realted issues in the compute domain
  <br>
  </p>
theme: jekyll-theme-minimal
